version: 2
updates:
  - package-ecosystem: "npm"
    directory: "vue/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "server/"
    schedule:
      interval: "daily"
