name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BOARDGAME_HOST }}
          username: ${{ secrets.BOARDGAME_USERNAME }}
          key: ${{ secrets.BOARDGAME_SSHKEY }}
          script: |
            cd boardgame
            git pull
            cd vue
            yarn install
            yarn build
            cd ../server
            yarn install
            yarn build
